fos_http_cache:
  cache_control:
    defaults:
      overwrite: true
    rules:
      - match:
          path: ^/api
        headers:
          cache_control: { public: true, max_age: 64000, s_maxage: 64000 }
          etag: "strong"
          vary: [ Accept-Encoding, Accept-Language ]