security:
  enable_authenticator_manager: true

  encoders:
    App\Entity\User:
      algorithm: md5
      encode_as_base64: false
      iterations: 0

  providers:
    users:
      entity:
        class: 'App\Entity\User'

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: '^/api/locations', roles: PUBLIC_ACCESS }
    - { path: '^/api/password-reset', roles: PUBLIC_ACCESS }
    - { path: '^/api/register', roles: PUBLIC_ACCESS }
    - { path: '^/api/login', roles: PUBLIC_ACCESS }
    - { path: '^/api', roles: IS_AUTHENTICATED_FULLY }