App\Entity\Ascent:
  attributes:
    id:
      groups: [ "default" ]
    type:
      groups: [ "default" ]
    score:
      groups: [ "default" ]
    user:
      groups: [ "default" ]
    behaviours:
      groups: [ "admin" ]