App\Entity\Boulder:
  attributes:
    id:
      groups: [ "default" ]
    name:
      groups: [ "default" ]
    grade:
      groups: [ "default" ]
    internalGrade:
      groups: [ "setter", "admin" ]
    holdType:
      groups: [ "default" ]
    startWall:
      groups: [ "default" ]
    endWall:
      groups: [ "default" ]
    createdAt:
      groups: [ "default" ]
    setters:
      groups: [ "default" ]