App\Entity\Boulder:
  attributes:
    id:
      groups: [ "default" ]
    name:
      groups: [ "default" ]
    grade:
      groups: [ "default" ]
    internalGrade:
      groups: [ "setterDefault", "adminDefault" ]
    holdType:
      groups: [ "default" ]
    startWall:
      groups: [ "default" ]
    endWall:
      groups: [ "default" ]
    setters:
      groups: [ "default" ]
    userAscent:
      groups: [ "default" ]
    currentPoints:
      groups: [ "default" ]
    points:
      groups: [ "default" ]
    tags:
      groups: [ "default", "detail" ]
    ascents:
      groups: [ "detail" ]
    comments:
      groups: [ "detail" ]
    status:
      groups: [ "setterDefault", "adminDefault" ]
    areas:
      groups: [ "default" ]
    readableIdentifier:
      groups: [ "detail", "adminDefault", "setterDefault" ]