App\Entity\HoldType:
  attributes:
    id:
      groups: [ "default" ]
    name:
      groups: [ "default" ]
    image:
      groups: [ "default" ]
    active:
      groups: [ "detail" ]
    behaviours:
      groups: [ "admin" ]