App\Entity\Setter:
  attributes:
    id:
      groups: [ "default" ]
    username:
      groups: [ "default" ]
    active:
      groups: [ "default" ]
    user:
      groups: [ "detail" ]
    behaviours:
      groups: [ "admin" ]