App\Entity\User:
  attributes:
    id:
      groups: [ "default" ]
    username:
      groups: [ "default" ]
    email:
      groups: [ "detail" ]
    image:
      groups: [ "detail" ]
    visible:
      groups: [ "detail" ]
    firstName:
      groups: [ "detail" ]
    lastName:
      groups: [ "detail" ]
    notifications:
      groups: [ "detail" ]
    roles:
      groups: [ "admin" ]