App\Entity\Wall:
  attributes:
    id:
      groups: [ "default" ]
    name:
      groups: [ "default" ]
    active:
      groups: [ "default" ]
    media:
      groups: [ "detail" ]
    description:
      groups: [ "detail" ]